### PR TITLE
Python is our macroprocessor

### PR DESCRIPTION
**Pull request by chsasank**
For macro processing, we use python for our macro definitions.  We use lisp syntax of unquote and unquote-splicing to achieve this. For example:

```
(c-lisp
    ,@(print_includes)
    (define ((main int))
        (declare res ,cudevice)
        (set res ,(myError (call print 5)))
        (ret 0)))
```

Define these variables in python file:

```py
cudevice = "int"

def myError(expr):
    return ("call", "error", expr)

def print_includes():
    return [
        ("define", (("print", "int"), ("n", "int"))),
        ("define", (("fprint", "float"), ("n", "float")))
    ]
```

gets expanded to

```
(c-lisp
  (define ((print int) (n int)))
  (define ((fprint float) (n float)))
  (define ((main int))
    (declare res int)
    (set res (call error (call print 5)))
    (ret 0)))
```

### CODE REVIEW

**Comment by chsasank** [comment]
Alternate syntax to make this literally a python file:

```python
def init_zeros(c, ldc):
    out = []
    for i in range(4):
        for j in range(4):
            ln = ("store", ("ptradd", c, ("add", i, ("mul", j, ldc))), 0.0)
            out.append(ln)
    return out


def store_vals(p, a, b, c, lda, ldb, ldc):
    out = []
    for i in range(4):
        for j in range(4):
            c_ij = ("ptradd", "c", ("add", i, ("mul", j, "ldc")))
            a_ip = ("ptradd", "a", ("add", i, ("mul", p, "lda")))
            b_pj = ("ptradd", "b", ("add", p, ("mul", j, "ldb")))
            ln = ("store", c_ij, ("fadd", ("load", c_ij), ("fmul", ("load", a_ip), ("load", b_pj))))
            out.append(ln)
    
    return out

prog = """
(c-lisp
    ;; Function to add dot products for a 4x4 block
    (define ((__add_dot4x4 void)
            (k int)
            (a (ptr float))
            (lda int)
            (b (ptr float))
            (ldb int)
            (c (ptr float))
            (ldc int))

        ,@(init_zeros c ldc)

        (for ((set p 0) (lt p k) (set p (add p 1)))
            ,@(store_vals p a b c lda ldb ldc))

        (ret))
    
    (define ((__kernel void)
            (a (ptr float))
            (b (ptr float))
            (c (ptr float))
            (m int)
            (n int)
            (k int))

        (declare i int)
        (declare j int)

        (declare lda int)
        (declare ldb int)
        (declare ldc int)

        (set lda m)
        (set ldb n)
        (set ldc k)

        (for ((set j 0) (lt j n) (set j (add j 4)))
            (for ((set i 0) (lt i m) (set i (add i 4)))
                (call __add_dot4x4 k 
                    (ptradd a (add i (mul 0 lda))) lda 
                    (ptradd b (mul j ldb)) ldb
                    (ptradd c (add i (mul j ldc))) ldc)))
        (ret)))
"""

print(display(macro_expand(parse(prog))))

```

Might be a good idea to do this because everything is in one single file.

**Comment by GlowingScrewdriver** [comment]
> Might be a good idea to do this because everything is in one single file.

On the other hand, the ability to split code over multiple files is an important capability IMO.
Embedding might make it simple for us for now, but I think separate files is definitely easier to work with.

**Comment by chsasank** [comment]
My problem is that we've had to put macro code in separate file and making this code unreadable. Want to be able to put everything related in one single place.

**Comment by chsasank** [comment]
Merging for now. Single sourcing/linking to be handled later.

**Pull request merged**
